import { readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PACKAGE_LOCK_PATH = join(ROOT, "package-lock.json");
const CARGO_MANIFEST_PATH = join(ROOT, "src-tauri", "Cargo.toml");
const NOTICE_PATH = join(ROOT, "THIRD_PARTY_NOTICES.md");

function fail(message) {
  throw new Error(message);
}

function readJson(filePath) {
  try {
    return JSON.parse(readFileSync(filePath, "utf8"));
  } catch (error) {
    fail(`Could not read ${filePath}: ${error.message}`);
  }
}

function cargoMetadata() {
  const result = spawnSync(
    "cargo",
    ["metadata", "--locked", "--manifest-path", CARGO_MANIFEST_PATH, "--format-version", "1"],
    {
      cwd: ROOT,
      encoding: "utf8",
      maxBuffer: 64 * 1024 * 1024,
      stdio: ["ignore", "pipe", "pipe"],
    },
  );
  if (result.error) fail(`Could not run cargo metadata: ${result.error.message}`);
  if (result.status !== 0) {
    fail(`cargo metadata failed with status ${result.status}.
${result.stderr}`);
  }
  try {
    return JSON.parse(result.stdout);
  } catch (error) {
    fail(`cargo metadata returned invalid JSON: ${error.message}`);
  }
}

function npmPackageName(lockKey) {
  const packagePath = lockKey.slice("node_modules/".length);
  const nestedMarker = packagePath.lastIndexOf("node_modules/");
  return nestedMarker === -1 ? packagePath : packagePath.slice(nestedMarker + "node_modules/".length);
}

function npmPackageUrl(name, version) {
  return `https://www.npmjs.com/package/${name}/v/${version}`;
}

function cargoPackageUrl(pkg) {
  const repository = typeof pkg.repository === "string" ? pkg.repository.replace(/\.git$/, "") : "";
  return repository.startsWith("https://") ? repository : `https://crates.io/crates/${pkg.name}/${pkg.version}`;
}

function licenseFor(pkg, source) {
  if (typeof pkg.license === "string" && pkg.license.trim()) return pkg.license.trim();
  if (typeof pkg.license_file === "string" && pkg.license_file.trim()) return `file:${pkg.license_file.trim()}`;
  fail(`${source} package ${pkg.name}@${pkg.version} has no declared license metadata.`);
}

function collectPackages() {
  const packageLock = readJson(PACKAGE_LOCK_PATH);
  const npm = Object.entries(packageLock.packages ?? [])
    .filter(([key, pkg]) => key.startsWith("node_modules/") && !pkg.link)
    .map(([key, pkg]) => ({
      ecosystem: "JavaScript",
      name: npmPackageName(key),
      version: pkg.version,
      license: licenseFor({ ...pkg, name: npmPackageName(key) }, "npm"),
      url: npmPackageUrl(npmPackageName(key), pkg.version),
    }));

  const metadata = cargoMetadata();
  const cargo = (metadata.packages ?? [])
    .filter((pkg) => pkg.source)
    .map((pkg) => ({
      ecosystem: "Rust",
      name: pkg.name,
      version: pkg.version,
      license: licenseFor(pkg, "Cargo"),
      url: cargoPackageUrl(pkg),
    }));

  return { npm, cargo };
}

function sortPackages(packages) {
  return [...packages].sort((left, right) =>
    left.license.localeCompare(right.license) ||
    left.name.localeCompare(right.name) ||
    left.version.localeCompare(right.version),
  );
}

function licenseLabel(license) {
  return `\`${license}\``;
}

function renderInventory(title, packages) {
  const lines = [`## ${title}`, ""];
  const byLicense = new Map();
  for (const pkg of sortPackages(packages)) {
    if (!byLicense.has(pkg.license)) byLicense.set(pkg.license, []);
    byLicense.get(pkg.license).push(pkg);
  }
  for (const [license, entries] of byLicense) {
    lines.push(`### ${licenseLabel(license)} (${entries.length})`, "");
    for (const pkg of entries) {
      lines.push(`- [\`${pkg.name}@${pkg.version}\`](${pkg.url}) — ${licenseLabel(pkg.license)}`);
    }
    lines.push("");
  }
  return lines;
}

function renderNotice() {
  const { npm, cargo } = collectPackages();
  const all = [...npm, ...cargo];
  const uniqueLicenses = new Set(all.map((pkg) => pkg.license));
  const lines = [
    "# Third-party notices",
    "",
    "> This file is generated by `npm run licenses` from `package-lock.json` and Cargo metadata. Do not edit it by hand.",
    "",
    `The resolved inventory contains ${npm.length} JavaScript package entries and ${cargo.length} Rust package entries across ${uniqueLicenses.size} license expressions. Build-only and test-only entries are retained so source and release artifacts keep a complete, lockfile-backed attribution record.`,
    "",
    "The license column uses the package's declared SPDX expression. Each package link points to its upstream package page or repository, where the complete license text and copyright notices are maintained. Refresh this file after any lockfile or dependency change and keep it with distributed Drop artifacts.",
    "",
    "This inventory covers third-party components only. Drop's own product license is not specified in the package or Cargo metadata and must be supplied separately by the project owner before distribution.",
    "",
    "## Directly bundled asset",
    "",
    "Drop bundles the Inter typeface through [`@fontsource/inter`](https://www.npmjs.com/package/@fontsource/inter). Inter is Copyright 2016 The Inter Project Authors and is distributed under the [SIL Open Font License, version 1.1](https://openfontlicense.org/).",
    "",
    ...renderInventory(`JavaScript lockfile inventory (${npm.length})`, npm),
    ...renderInventory(`Cargo lockfile inventory (${cargo.length})`, cargo),
  ];
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

function main(command) {
  const expected = renderNotice();
  if (command === "generate") {
    writeFileSync(NOTICE_PATH, expected, "utf8");
    console.log(`Generated ${NOTICE_PATH}`);
    return;
  }
  if (command === "check") {
    let actual;
    try {
      actual = readFileSync(NOTICE_PATH, "utf8");
    } catch (error) {
      fail(`Could not read ${NOTICE_PATH}: ${error.message}`);
    }
    if (actual !== expected) {
      fail("THIRD_PARTY_NOTICES.md is stale; run npm run licenses and commit the generated file.");
    }
    console.log("Third-party notices are current.");
    return;
  }
  fail("Usage: node scripts/licenses.mjs <generate|check>");
}

try {
  main(process.argv[2]);
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
}
